### ISSUE TITLE
cannot attach to 7nodes. genesis block not found 

### ISSUE THREAD

**Issue by Jaypov** [jpmorganchase/cakeshop#109]
#### Description of problem
When attempting to attach cakeshop to 7nodes (running both cakeshop and 7nodes in the same vagrant machine, which was configured by the 7nodes script), cakeshop cannot find the genesis block. even when changing the data dir in the file `$CAKESHOP/docker/cakeshop/data/local/application.properties` to the data dir of 7nodes.

upon running the war `java -jar cakeshop.war` the `application.properties` files is overwritten, changing the data dir back to its original path

#### Expected behavior
Cakeshop to attach to a single 7nodes node

#### Actual behavior
Cakeshop fails to fully initialise as it cannot read the genesis block file

#### Steps to reproduce the behavior
1. install 7nodes following the instructions on the [wikki](https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes)
2. download [cakeshop.zip](https://github.com/jpmorganchase/cakeshop/releases/tag/v0.11.0) `wget https://github.com/jpmorganchase/cakeshop/archive/v0.11.0.zip`
3. build following build instructions [build.MD](https://github.com/jpmorganchase/cakeshop/blob/master/docs/building.md)
4. install [solc](https://www.npmjs.com/package/solc) globally to fix [solc bug](https://github.com/jpmorganchase/cakeshop/issues/87)
5. Follow [attach](https://github.com/jpmorganchase/cakeshop/issues/87) instructions for running cakeshop (from $CAKESHOP/docker/cakeshop dir) 

#### System information

Cakeshop version / commit hash: 0.11.0 / d74224e

Cakeshop runtime configuration: attach mode

Geth/Quorum version testing against: 
```
Geth
Version: 1.8.18-stable
Quorum Version: 2.2.4
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.9.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

Cakeshop OS & Version: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

Browser OS & Version: N/A

#### Backtrace/logs
[Gist](https://gist.github.com/Jaypov/be09381b05ce890dc52a8ba0b489920c)

**Comment by bmcd87** [comment]
Yeah, in attached mode a genesis.json file shouldn't be required. Will look into this issue. Thanks!

**Comment by Jaypov** [comment]
👍Temporarily solved the issue by copying gensis file from `{Quorum-examples}/7nodes/istanbul-genesis.json`  file to `{cakeshop}/docker/cakeshop/data/local/genesis_block.json`

**Comment by bmcd87** [comment]
This should be fixed in the latest release
