### ISSUE TITLE
sample contracts (SimpleStorage/Greeter) cannot be deployed/registered

### ISSUE THREAD

**Issue by ice09** [jpmorganchase/cakeshop#12]
#### Description of problem

Trying to deploy the sample contracts, already the simple ones (Greeter/SimpleStorage) don't work.

#### Expected behavior

Contract is deployed (registered?) and can be interacted with.

#### Actual behavior

1. Greeter does work till deployment (address is displayed and contract is correctly deployed), but then a server error occurs (at the registration step?), so no interaction is possible.
2. SimpleStorage cannot be deployed, error is unknown (a warning in the logs says that "String" is wrong type for "for private", but nothing was written in the corresponding textbox)

No useful logging due to spamming with empty trx exceptions (probably during REST trx get requests).

#### Steps to reproduce the behavior

Deploy of sample contracts Greeter or SimpleStorage in Ropsten (Geth Attach mode).

#### System information

Cakeshop version or commit hash: e82a29d8d0ce2f8b4f7f51e1b846706028ee8095

Geth/Quorum version testing against: 1.5.5-stable

Cakeshop OS & Version: Ubuntu 16.04 LTS

Browser OS & Version: Chromium / not browser related

#### Backtrace/logs

will provide on request, difficult due to the log spamming with empty trx exceptions.

**Comment by nv1620** [comment]
I am facing a similar issue but only with a few of my custom contracts. The contracts are deployed successfully but not registered. It makes it impossible to use Cakeshop APIs on these contracts.

**Comment by chetan** [comment]
@nv1620 Which version of cakeshop are you using? I just cut 0.9.1 yesterday. Please give that version a try and report back

**Comment by chetan** [comment]
@ice09 wrote:


> 1. Greeter does work till deployment (address is displayed and contract is correctly deployed), but then a server error occurs (at the registration step?), so no interaction is possible.

When you switched to the latest version, did you keep your old data around or did you wipe it out?

> 2. SimpleStorage cannot be deployed, error is unknown (a warning in the logs says that "String" is wrong type for "for private", but nothing was written in the corresponding textbox)

Sounds like a bug. Maybe there was some whitespace that got passed in by accident. I'll have to double check that.

**Comment by chetan** [comment]
@ice09 FYI, I also added a bunch of documentation today of the various configuration options, including some info about the registry: 

https://github.com/jpmorganchase/cakeshop/blob/master/docs/configuration.md#contract-registry

As of the latest build (the version you ran is fine) it should also print some startup messages showing which registry address is being used. Something like this:

```
 INFO 2017-01-04 20:46:03,396 [main] (BlockchainInitializerTask.java:124) Loaded contract registry address 0x098da5468f564063e4c35af412bdc409d7a6d89c
```

**Comment by chetan** [comment]
> 2. SimpleStorage cannot be deployed, error is unknown (a warning in the logs says that "String" is wrong type for "for private", but nothing was written in the corresponding textbox)

I've seen this warning in the past but am not able to recreate it now. In any case, it can be safely ignored since you are using vanilla geth. The "private for" field is only relevant when using Quorum and will eventually be hidden when not running on it.

**Comment by ice09** [comment]
@chetan I am sure to have deleted the old data before trying the new "master"-branch version.
Regarding the contract registry, should I let you know the startup message? I will have to retry at home then.

**Comment by nv1620** [comment]
@chetan I directly downloaded the war. I noticed that the contract registry works for 4 public methods but fails for 5 public methods(without throwing any error). The last prompt I get is "Waiting for contract to be registered".

What do you think could be the issue?

**Comment by AugustoL** [comment]
Having the same error here.

**Comment by StevenBerryman** [comment]
I'm having the same issue when deploying the Token Contract. The contract gets deployed to the chain but never gets registered and I can't see any errors in the node or cakeshop logs. I can get the SimpleStorage Contract registered but as soon as the contract gets beyond a certain length it fails to register it. The last prompt I get is "Waiting for contract to be registered".

I'm using the latest version 0.9.1

**Comment by belyak** [comment]
I have the same problem -- "Waiting for contract to be registered" with sample Bank contract.
Also it can be compiled only if I remove withdraw method - with withdraw compiler output contains only warning (unused .send result) and do not shows final compilation result.
