### ISSUE TITLE
Can cakeshop create a network like quorum maker?

### ISSUE THREAD

**Issue by RealDeanZhao** [jpmorganchase/cakeshop#123]
Quorum maker only support RAFT and older version of quorum.
Will cakeshop support one click network setup?

**Comment by bmcd87** [comment]
Not at the moment, but we're looking into adding this feature.

**Comment by fredhampton** [comment]
Is one click network setup on the product road map ?

**Comment by bmcd87** [comment]
So it's not part of cakeshop, but we have a new command-line tool called Quorum Wizard that helps you create a network. It is only for creating non-production, local development networks. But it should help people get started with Quorum.

Check it out here: https://github.com/jpmorganchase/quorum-wizard
