### ISSUE TITLE
Customize cakeshop

### ISSUE THREAD

**Issue by dvgoyeneche** [jpmorganchase/cakeshop#131]
Is it possible to customize the cakeshop web app? For example to change colors, insert brand Name...

thanks

**Comment by fixanoid** [comment]
Hi @dvgoyeneche, as long as you follow the license rules, you are free to clone and do whatever you may need for your needs.

**Comment by fixanoid** [comment]
Just for reference, UI lives in cakeshop-api/src/main/webapp and is a plain vanilla webpack build.
