### ISSUE TITLE
Geth failed to start when using Docker image

### ISSUE THREAD

**Issue by weeix** [jpmorganchase/cakeshop#142]
#### Description of problem

Encountered "Geth RPC did not start within 10000ms" error when using *quorumengineering/cakeshop* Docker image.

#### Expected behavior

Able to access Cakeshop via browser after starting a container with the image.

#### Actual behavior

Screenshot when visiting `http://192.168.99.100:8080`:

![cakeshop-browser](https://user-images.githubusercontent.com/6592791/68544769-3d652400-03f9-11ea-8bf2-28fed0517bd6.png)

Error messages printed:

> [2019-11-10T13:13:39,555] Geth RPC did not start within 10000ms
> 
> [2019-11-10T13:13:39,556] Ethereum failed to start
> 
> [2019-11-10T13:13:39,556] GETH FAILED TO START

#### Steps to reproduce the behavior

1. Create *data/* directory
1. Execute this command:

        docker run -p 8080:8080 -v "$PWD/data":/opt/cakeshop/data quorumengineering/cakeshop

#### System information

Cakeshop version or commit hash: 0.11.0

Cakeshop runtime configuration: stand alone

Geth/Quorum version testing against: Geth 1.8.18-stable / Quorum 2.2.4

Cakeshop OS & Version: Windows 10 Pro (1903)

Browser OS & Version: Chrome 78.0.3904.97 (Official Build) (64-bit)

Docker Toolbox Version: 19.03.1

#### Backtrace/logs

[cakeshop-docker.log](https://gist.github.com/weeix/44b9458d61c994cf982faa5924e047c3)

**Comment by bmcd87** [comment]
i just updated the dockerhub repo with 0.11.0-RC2. Please try that version and let me know if it fixes it (you can also just use the 'latest' tag)
