### ISSUE TITLE
JSON Parse Error on sandbox, not compiling contracts

### ISSUE THREAD

**Issue by AugustoL** [jpmorganchase/cakeshop#15]
#### Description of problem
An exeception appears when im trying to compile my contracts on sandbox, the code is correct because it compiles successfully with solc and browser solidity.

JsonParseException: Unexpected end-of-input: was expecting closing quote for a string value
 at [Source: java.io.StringReader@3e88298e; line: 1, column: 67073]

#### Expected behavior

Compile correctly.

#### Actual behavior

Getting exception: 
JsonParseException: Unexpected end-of-input: was expecting closing quote for a string value
 at [Source: java.io.StringReader@3e88298e; line: 1, column: 67073]

#### Steps to reproduce the behavior

Try to compile this https://gist.github.com/anonymous/9e1a26f067c6d9e3f89f9e8f804c003e

#### System information

Cakeshop version or commit hash: v0.9.1

Geth/Quorum version testing against: 

```
Geth
Version: 1.5.0-unstable
Git Commit: 6d0bd810484f4c56f7c9aebc229e1bdc56832ced
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.6
```

Cakeshop OS & Version: Linux, ubuntu 16.04

Browser OS & Version: Firefox

**Comment by tylobban** [comment]
Apologies for delay. The error is due to the fact that we’re using an older install of solc compiler (0.3.x). While this is going to get addressed in the next release, a fixed version may be built from here: https://github.com/fixanoid/cakeshop/tree/quorum-ui.

**Comment by VeraBE** [comment]
@tylobban When I try to compile Bank.sol with the version you recommend I get: ":11:61: Error: Expected token Semicolon got 'RBrace' modifier only_contract_owner { if (msg.sender == owner) _ }". And after deleting the function only_contract_owner and all its appearances: "JsonParseException: Unexpected end-of-input: was expecting closing quote for a string value at [Source: java.io.StringReader@35383171; line: 1, column: 81001]"".
