### ISSUE TITLE
Problem deploying Registry on attached Quorum

### ISSUE THREAD

**Issue by flyswatter** [jpmorganchase/cakeshop#17]
Hi There,

I can't find any documentation of how to deploy a Smart Contract Registry to a quorum if it does not already exist.  I think it would be in `application.properties`, but [the config docs on the registry](https://github.com/jpmorganchase/cakeshop/blob/master/docs/configuration.md#contract-registry) do not cover how to deploy the registry.

I would expect deploying requires an account with some ether, so I would expect EITHER:
- a config option for specifying an account with sufficient ether.
- a link to the Quorum docs about deploying the registry.

I can't find either.

Thanks for your time!

**Comment by flyswatter** [comment]
To give extra context, the last two logs I'm seeing are:
```
cakeshop_1  |  INFO 2017-03-02 19:11:11,022 [main] (BlockchainInitializerTask.java:120) Contract registry address not found
cakeshop_1  |  INFO 2017-03-02 19:11:11,022 [main] (BlockchainInitializerTask.java:149) ContractRegistry not found on chain
```

Looking at [your source code](https://github.com/jpmorganchase/cakeshop/blob/257d1326e5bc22a527e99d30322e29da75d6e804/cakeshop-api/src/main/java/com/jpmorgan/cakeshop/service/task/BlockchainInitializerTask.java#L149), it looks like this is where you try to deploy, but I'm getting neither these info nor error logs after, so I'm curious what could be going wrong.

**Comment by flyswatter** [comment]
Another observation:

And looking at the source, it looks like right after that is when it tries to deploy, but I’m not getting the logs or the errors after that point.

I do notice that part of the deploy attempt has the comment “make sure mining is enabled”.  Does this mean cakeshop needs mining enabled *even if it is running in attached mode*?  I think that's a contradiction, so this might be the problem?  I see no logs after this point, so it may be hanging [on this line](https://github.com/jpmorganchase/cakeshop/blob/257d1326e5bc22a527e99d30322e29da75d6e804/cakeshop-api/src/main/java/com/jpmorgan/cakeshop/service/task/BlockchainInitializerTask.java#L152).

Maybe that’s the problem, the code seems to only be able to deploy the registry if running in hosted geth mode?

**Comment by tylobban** [comment]
Hi flyswatter, thanks for posting.
 
Several answers:
- depending on the version of cakeshop its either deployed at startup via first several transactions or through genesis file. Here is the actual contract location: https://github.com/jpmorganchase/cakeshop/tree/master/cakeshop-api/src/main/resources/contracts
 
- In attach mode, you need to specify an environment config var that provides registry address. This is documented in https://github.com/jpmorganchase/cakeshop/wiki/Getting-Started#multi-instance-setup. look for CONTRACT_REGISTRY
 
- Finally, we have a Quorum based Cakeshop fork soon to be pulled into here, but you may check it out now: https://github.com/fixanoid/cakeshop/tree/quorum-ui. This fork simplifies running Cakeshop with Quorum under the hood

**Comment by flyswatter** [comment]
Oh, these solidity files should be perfect for deploying our own.

**Comment by flyswatter** [comment]
Small note:  Publishing these contracts on my own would be easier if the registry contract was deployed to [the ethereum package manager](https://www.ethpm.com/registry), and I think posting it there would be a great gift to your users.

**Comment by flyswatter** [comment]
Alright, I deployed the registry (with browser-solidity and metamask!) and I've got this now:

```

  |  INFO 2017-03-02 23:11:03,810 [main] (BlockchainInitializerTask.java:124) Loaded contract registry address 0x944313e412e50bf6ca8958d8ec646933e5fa3c58
  |  INFO 2017-03-02 23:11:03,817 [main] (BlockchainInitializerTask.java:88 ) Storing existing wallet account balances
  |
  |
  |                   ,%%%%%%%%,
  |                 ,%%/\%%%%/\%%
  |                ,%%%\c "" J/%%%    ,,,,,,,
  |       %.       %%%%/ 6  6 \%%%    |||||||
  |       `%%.     %%%%    _  |%%%  @@@@@@@@@@@
  |        `%%     `%%%%(__Y__)%%'  {~*~*~*~*~}
  |        //       ;%%%%`\-/%%%' @@@@@@@@@@@@@@@@
  |       ((       /  `%%%%%%%'   {~* CAKESHOP *~}
  |        \\    .'          |    {     OPEN     }
  |         \\  /       \  | |    {~~*~~*~~*~~*~~}
  |          \\/         ) | |    @@@@@@@@@@@@@@@
  |           \         /_ | |__      __) (__
  |           (___________)))))))    /_______\
  |
  |           CAKESHOP
  |           version:     0.9.1
  |           build id:    6c7a88ee8b317fe2b69c97fe1e838112cb655411
  |           build date:  2017-01-03T20:43:36.806+0000
  |           url:         http://172.18.0.2:8080/cakeshop/
  |

```

I'm getting a 404 on port :8080, but can I safely assume the dag is being generated?

**Comment by flyswatter** [comment]
It eventually worked!  Yay!

I guess if anything would "fix" this issue it would be the links you sent me being more prominent, but you were prompt, so I'll just close it for now, thanks so much for your great replies.
