### ISSUE TITLE
Not handling arrays properly

### ISSUE THREAD

**Issue by VeraBE** [jpmorganchase/cakeshop#27]
#### Description of problem
Cakeshop doesn't respond when trying to read values from a public array variable.

#### Expected behavior
Should read the value and show in "Paper tape" and "Contract state".

#### Actual behavior
Array doesn't appear in "Contract state" and doesn't respond when trying to read its values.

#### Steps to reproduce the behavior
Deploy:
```
contract TestArray {
  int[] public array;

  function addElement(int element) {
    array.push(element);
  }
}
```
Using the "Transact" box add any number to the array. After that try reading it using the "Read" buttom next to "array" and giving it "0" as argument.

#### System information

Cakeshop version or commit hash:  0.9.1

Geth/Quorum version testing against: 
> Geth
> Version: 1.5.0-unstable
> Git Commit: b6286320efc4189419a8e0f7f28f9af50f71b3ff
> Protocol Versions: [63 62]
> Network Id: 1
> Go Version: go1.7.3
> OS: linux
> GOPATH=
> GOROOT=/usr/local/go

Cakeshop OS & Version: Ubuntu 16.04

Browser OS & Version: Google Chrome 57.0.2987.133 (64-bit)

**Comment by fixanoid** [comment]
fixed via mikkazan's pull.
