### ISSUE TITLE
webpack failed when build

### ISSUE THREAD

**Issue by bigstar119** [jpmorganchase/cakeshop#31]
Hi ,i use webpack command to build the ui . i got an error ,the detail is under:

E:\develop\eclipse_golang\workspace_new\cakeshop-0.9.1\cakeshop-api\src\main\web
app>webpack
Hash: 3bb7e8e1749d59e297f5
Version: webpack 1.15.0
Time: 12592ms
           Asset     Size  Chunks             Chunk Names
    index-gen.js  3.05 MB       0  [emitted]  main
index-gen.js.map  3.74 MB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built]
 [242] ./js/widgets ^\.\/.*$ 1.06 kB {0} [optional] [built]
    + 327 hidden modules

ERROR in ./js/index.js
**Module not found: Error: Cannot resolve 'file' or 'directory' ./vendor/cakeshop**
in E:\develop\eclipse_golang\workspace_new\cakeshop-0.9.1\cakeshop-api\src\main\
webapp\js
 @ ./js/index.js 21:0-28

this error point to the line **import './vendor/cakeshop';**,and under vendor directory reallly do not have
cakeshop.js ..why this problem,  how can i fix it?

**Comment by tylobban** [comment]
Hi,
The vendor/cakeshop.js is a separate build that needs to be executed either via an already existing process or manually, whichever you are more comfortable with. The source of it is here: https://github.com/jpmorganchase/cakeshop/tree/master/cakeshop-client-js

Regular build for it is maven based, so just cd into this folder and run mvn install. Manual build requires you to run npm install and then gulp build from https://github.com/jpmorganchase/cakeshop/tree/master/cakeshop-client-js/src/main/javascript as per [these ](https://github.com/jpmorganchase/cakeshop/blob/master/cakeshop-client-js/README.md)instructions.

Alternatively you can simply download the latest [release ](https://github.com/jpmorganchase/cakeshop/releases) and [run ](https://github.com/jpmorganchase/cakeshop#running-via-spring-boot) the war file.

**Comment by bigstar119** [comment]
thank you for answer..i rebuild cakeshop-client-js and fixed the problem.
