### ISSUE TITLE
constellation settings for 7 nodes example

### ISSUE THREAD

**Issue by riceman33** [jpmorganchase/cakeshop#33]
#### Description of problem
I am running cakeshop in attached mode to connect to 3 of the 7 nodes in the 7 nodes example. I think each cakeshop instance is not correctly displaying the relevant constellation node. 

#### Expected behavior
In the Peers tab on each web ui, I would have expected the constellation nodes have different ports  (e.g. http://127.0.0.1:9000/, http://127.0.0.1:9001/, http://127.0.0.1:9002)

#### Actual behavior
In the Peers tab on each web ui, it shows http://127.0.0.1:9000/
(paste logs at end)

#### Steps to reproduce the behavior
Navigate to Peers tab on cakeshop

#### System information

Cakeshop version or commit hash: Cakeshop 0.10.0, Build 48b7fd7e

Cakeshop runtime configuration: multi instance and attach mode

Geth/Quorum version testing against: [run `geth version` or copy from Node Info in UI]

Cakeshop OS & Version: macOS Sierra

Browser OS & Version: Chrome Version 58.0.3029.110 (64-bit)

#### Backtrace/logs

Copy all relevant log output. Use [Gist](https://gist.github.com/) for longer logs.

```
[stacktrace/logs]
```

**Comment by fixanoid** [comment]
Hi! Just checking, but did you properly configure the applicaiton.properties file to connect to each specific node?

**Comment by riceman33** [comment]
Yes, I believe so according to the documentation. I changed the geth.url on each to match the rpcport for each geth instance. Should I also change the geth.node.port property (currently set to 30303) to match the geth instance port?

**Comment by fixanoid** [comment]
We've not updated the docs for the new release yet, but you now also need to specify constellation url as follows, per node, it defaults to http://127.0.0.1:9000:

-Dgeth.constelaltion.url=http://127.0.0.1:<new_port>

Alternatively, modifying application.properties should do. Please note, we're not fully done here, so there may be bugs in this pre-release, especially when attaching to running nodes.
