### ISSUE TITLE
Unable to connect to external quorum node

### ISSUE THREAD

**Issue by haldhar** [jpmorganchase/cakeshop#36]
Trying to connect the quorum node running on the other machine, then cake shop, log shows that node added successfully but unable to see the node info on the cake shop.

**Comment by fixanoid** [comment]
Hi @haldhar, could you tell me what exactly you were attempting to do? What version of cakeshop is in use? Logs? Thanks,

Felix.

**Comment by haldhar** [comment]
1) Running one quorum node(machine 1).
2) Running cake shop on another machine(machine1).
3)Trying to add machine1 quorum node using cake shop on machine2.
4)Unable to see the quorum of machine1 under cake shop running on machine2.

**Comment by fixanoid** [comment]
Hey @haldhar , I'll take a look and report my findings to you in a bit.
