### ISSUE TITLE
CORS blocking on Cakeshop API

### ISSUE THREAD

**Issue by rafiduck** [jpmorganchase/cakeshop#37]
#### Description of problem
Impossible to query Cakeshop API from localhost to localhost

#### Expected behavior
Queries issued from webpage hosted at http://localhost:3000 to Cakeshop API running at http://localhost:8080/cakeshop/api would be accepted 

#### Actual behavior
Queries issued from webpage hosted at http://localhost:3000 to Cakeshop API running at http://localhost:8080/cakeshop/api are forbidden, seemingly by CORS mechanism

#### Steps to reproduce the behavior
1. Fire up a Cakeshop interface (java -jar cakeshop.war)
2. Fire up (i.e. serve from NodeJS on port 3000) a very simple web page containing a jQuery POST call : 

`$.ajax({
	url: "http://localhost:8080/cakeshop/api/contract/list", 
	type: "POST", 
	headers: { "Content-type":"application/json" },
	success: function(data) { console.log(data) }
})`

#### System information

Cakeshop version or commit hash: 0.9.1
Cakeshop runtime configuration: standalone or attach
Geth/Quorum version testing against: v1.5.4-stable-b70acf3c/windows/go1.7.3
Cakeshop OS & Version: tried on Windows 10 and Ubuntu 16.04.2, both serving html file with nodeJS
Browser OS & Version: Chrome & Firefox

#### Backtrace/logs

Response in Chrome : 
OPTIONS http://localhost:8080/cakeshop/api/contract/list 403 (Forbidden)
XMLHttpRequest cannot load http://localhost:8080/cakeshop/api/contract/list. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403.

Would you know how I could allow CORS requests to the Cakeshop API?

Many thanks for your help

**Comment by fixanoid** [comment]
Hi @rafiduck, this is intended functionality with default start. If you'd like to enable CORS, please update your application.properties. See: https://github.com/jpmorganchase/cakeshop/blob/master/cakeshop-api/src/main/resources/config/application.properties

**Comment by rafiduck** [comment]
Are we talking about the application.properties file that is documented @ https://github.com/jpmorganchase/cakeshop/blob/master/docs/configuration.md ?
If yes, I can't see where CORS would be enabled (I see two geth.cors lines, but I'm trying to enable CORS on Cakeshop, not geth) ...
Furthermore, I would need to enable this CORS authorization in both managed and unmanaged modes - is this possible?

Many thanks

**Comment by fixanoid** [comment]
Hey @rafiduck, so the documentation is a bit light, so it gonna go on the todo list of updates.

This note: # Enable CORS for geth RPC endpoint [managed only] -- is not correct, entering URL there will open up cakeshop APIs for CORS, since cakeshop itself requires CORS setting for geth, overwriting it is a pain, but possible via appending whatever you need to pass to geth with this property: geth.params.extra=

**Comment by rafiduck** [comment]
Thanks @fixanoid 
I tried the following parameters in application.properties : 
'geth.cors.enabled=true
geth.cors.url=*
endpoints.cors.allowed-origins=*
endpoints.cors.allowed-methods=*
'

But still receive the same 403 forbidden response when querying Cakeshop...

**Comment by fixanoid** [comment]
Will test in a bit, but could oyu try your actual url instead of *?

geth.cors.url=http://localhost:3000

**Comment by rafiduck** [comment]
Unfortunately same result :(

**Comment by rafiduck** [comment]
Actually something starts puzzling me: even if I serve my html file from a dockerized nodejs (172.17.0.3:3000) and query dockerized Cakeshop (172.17.0.4:8080/cakeshop) from it, I get the same error : 

` XMLHttpRequest cannot load http://172.17.0.4:8080/cakeshop/api/contract/list. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://172.17.0.3:3000' is therefore not allowed access. The response had HTTP status code 403. `

I doubt that no one ever tried to create a webapp and connect it to Cakeshop API...

**Comment by rafiduck** [comment]
Nailed it down to line 72 in cakeshop/cakeshop-api/src/main/java/com/jpmorgan/cakeshop/config/WebConfig.java : 

`@Override
    public void addCorsMappings(CorsRegistry registry) {
        if (Boolean.valueOf(env.getProperty("geth.cors.enabled:true"))) {
            registry.addMapping("/**")
                    .allowedOrigins(env.getProperty("geth.cors.url"))
                    .allowedMethods("POST");
        }
    }
`

Is the env.getProperty("geth.cors.enabled:true") statement correct?

**Comment by fixanoid** [comment]
Hey @rafiduck , my apologies, finally got around at looking what we did for CORS and had to patch it up a bit in this commit: https://github.com/jpmorganchase/cakeshop/commit/784ea7677ad788f1ad8e43b0b7b447e3d75c4c66

You should rebuild and you'll be good to go. The config patch I made will allow you to set the CORS config via the applications.properties OR via environmental var like so:
-Dgeth.cors.enabled=true -Dgeth.cors.url=http://localhost:8000

As far as I know, OPTIONS is only required if you are in the browser, so this is why we never allowed it before -- the current clients using Cakeshop API use server side to communicate with the API...

**Comment by rafiduck** [comment]
Thanks - had kind of figured it out as you can see above - however building is kind of a challenge for me - I succeeded in creating my new cakeshop.war, but when launching it would not find epoch-charting - it seems that `"epoch-charting": "github:fixanoid/epoch"` in cakeshop/cakeshop-api/src/main/webapp/package.json refers to a repo not available any more

**Comment by rafiduck** [comment]
Got it working by building quorum-ui branch with latest commits. Many thanks!
