### ISSUE TITLE
Unable to pass array arguments to contract

### ISSUE THREAD

**Issue by rafiduck** [jpmorganchase/cakeshop#38]
Good afternoon,
I successfully deployed a contract with a bytes32[2] array as first argument : 
`pragma solidity ^0.4.9;
contract test {
  function test(){
  }
  function create(bytes32[2] input) returns (uint res) {
    res = input[0];
    return res;
  }
}`
When curl-ing it using master-branch war, I can transact with this contract by passing the argument like that: 
` curl (...) """args""": "["["""1""","""2"""]"]" `
But this will fail using the quorum-ui branch war, with a ""List value expected for type bytes32[2]" error
Would you know how I should now be passing array arguments to contracts under quorum-ui branch version of the API ?
Many thanks

**Comment by fixanoid** [comment]
This issue is now resolved, please pull and rebuild or download new release from: https://github.com/jpmorganchase/cakeshop/releases

**Comment by veerakishorerk** [comment]
I am unable to deploy my solidity code in cake shop.if we deploy with minimal input parameters working fine.but my solidity code having lot of functions.
And how to view contracts deployed from front end application.
