### ISSUE TITLE
Contract does not exist

### ISSUE THREAD

**Issue by ice09** [jpmorganchase/cakeshop#4]
#### System information

Cakeshop version or commit hash: 0.9.0

Geth/Quorum version testing against: 1.5.5-stable

OS & Version: Ubuntu 16.04 LTS

#### Expected behavior

no log statements

#### Actual behavior

log statements, cmp. "logs"

#### Steps to reproduce the behavior

Start cakeshop in attach mode.
Deploy contract
Stop cakeshop
Restart cakeshop

#### Backtrace/logs

```
/cakeshop/api/contract/list
 WARN 2016-12-19 20:59:26,261 [BlockSaver-42] (SavingBlockListener.java:118) Failed to load transaction details for tx
com.jpmorgan.cakeshop.error.APIException: Contract does not exist at 0xc47aa6c1987ec4737b40a327620c31fd1995602f
	at com.jpmorgan.cakeshop.service.impl.ContractServiceImpl.get(ContractServiceImpl.java:228)
```

**Comment by rfikki** [comment]
I can confirm this error repeats in the terminal on Windows.

**Comment by chetan** [comment]
I believe the fix I pushed should fix though, there may be other issues with working against the testnet. I need to sync that still and verify that things work as expected.

**Comment by ice09** [comment]
what is the best possibility to check, should I wait for a tag/nightly build or just build myself?

**Comment by chetan** [comment]
@ice09 I'll be cutting a new release after the holidays, so until then, the best option is to run from source. Building is fairly easy, whether running locally or for docker. 

#### loccal build:
`mvn -DskipTests clean package`

#### docker build:
https://github.com/jpmorganchase/cakeshop/blob/master/docs/building.md#building-a-docker-image
