### ISSUE TITLE
test fails when using "mvn package"

### ISSUE THREAD

**Issue by briantmali** [jpmorganchase/cakeshop#41]
When using "mvn package" to build war file, 
"
Testing solc compiler binary
FAILED
" was found

"
solc.path: cakeshop/cakeshop-api/target/classes/geth/solc/node_modules/solc-cli/bin/solc
solc.version: !!! unable to read solc version !!!
"
Try to locate the solc, I found there is not folder like "solc-cli", there is a  folder named "solc-cakeshop-cli", should I use it?

Cakeshop Version:0.9.1

**Comment by fixanoid** [comment]
Hi @briantmali 0.9.1 is currently unbuildable due to dependencies changing. Please build from the quorum-ui branch. This will be updated in the next few days.

**Comment by briantmali** [comment]
@fixanoid Thank you very much for your quick answer.
I will try the quorum-ui one.

**Comment by fixanoid** [comment]
Hey @briantmali, master is now up to date and should be buildable.
