### ISSUE TITLE
Attach Cakeshop deployed via Webserver to an(some) already running Node(s)?

### ISSUE THREAD

**Issue by CaptainMNB** [jpmorganchase/cakeshop#49]
#### Description of problem

I was wondering if it is possible to start Cakeshop like described here (https://github.com/jpmorganchase/cakeshop/blob/master/README.md) via a webserver but still manage to attach to an already running quorum node.

Side question: Is there another place/discussion forum to ask simple quorum oder cakeshop questions?
If so, please let me know about it!

#### Expected behavior

Run a quorum network with different nodes. Deploy cakeshop via an own webserver. Attach cakeshop to one (and later more) nodes of the running network. 

#### Actual behavior

Starting Cakeshop via the tutorial linked above starts the webserver and Cakeshop. However, this method starts in 'managed mode' and only gives access to a casual ethereum node as far as I know. 
(There is nothing wrong with that but it is just not the use case I am trying to create)

#### Steps to reproduce the behavior

Follow the tutorial steps linked above. 

#### System information

Cakeshop 0.10.0 Build 8d2a5ab

Cakeshop runtime configuration: stand alone via tomcat webserver but the goal is to somehow run in attach mode via the webserver

OS Version: Windows

Browser Version: Chrome/Firefoxi

**Comment by andrej-zirko** [comment]
Were you able to resolve this? Is it possible to attach cakeshop to already running node?

**Comment by bmcd87** [comment]
This should work already: https://github.com/jpmorganchase/cakeshop/wiki/Getting-Started#attach-mode
