### ISSUE TITLE
solc daemon doesn't clean up

### ISSUE THREAD

**Issue by chetan** [jpmorganchase/cakeshop#5]
As reported by @rfikki in https://github.com/jpmorganchase/cakeshop/issues/2#issuecomment-268064910

**Comment by ice09** [comment]
Just to let you know: this does not happen on Windows alone, I have this issue on Ubuntu 16.04 LTS. It's quite annoying, for whoever has this problem

- `lsof data/geth/bin/linux/node`
- kill -9 PID

then you can restart with java -jar cakeshop.war
Happens reproducibly all times after stopping with CTRL+C

**Comment by chetan** [comment]
@ice09 yup, looks like there's a race condition on shutdown. Sometimes (frequently?) cleanup doesn't happen in time and the process just exits leaving node/solc running.
