### ISSUE TITLE
Failed to load cakeshop in Tomcat8, Mac OS X 10.12

### ISSUE THREAD

**Issue by vobbilis** [jpmorganchase/cakeshop#53]
#### Description of problem
cakeshop fails to deploy with Tomcat8 on MAC OS X 

#### Expected behavior
Expect Tomcat to successfully deploy cakeshop

#### Actual behavior
WAR deploy fails

#### Steps to reproduce the behavior
Install tomcat8 using brew
Install SpringBoot using brew
Install java using brew

Add the following options:
JAVA_OPTS="$JAVA_OPTS -Dspring.profiles.active=local -Deth.config.dir=/private/tmp/tomcat8"

Modify geth.identity in /tmp/tomcat8/local/application.properties:
...
geth.identity=testckshop123
...

chmod 777 /private/tmp/tomcat8

#### System information
MAC OS X 10.12.6 (x86_64)

Cakeshop runtime configuration: [stand alone or attach mode]
standalone

#### Backtrace/logs
tests-MacBook-Pro-2:bin $ catalina run
Using CATALINA_BASE:   /usr/local/Cellar/tomcat/8.5.23/libexec
Using CATALINA_HOME:   /usr/local/Cellar/tomcat/8.5.23/libexec
Using CATALINA_TMPDIR: /usr/local/Cellar/tomcat/8.5.23/libexec/temp
Using JRE_HOME:        /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
Using CLASSPATH:       /usr/local/Cellar/tomcat/8.5.23/libexec/bin/bootstrap.jar:/usr/local/Cellar/tomcat/8.5.23/libexec/bin/tomcat-juli.jar
05-Oct-2017 09:36:17.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.23
05-Oct-2017 09:36:17.607 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 28 2017 10:30:11 UTC
05-Oct-2017 09:36:17.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.23.0
05-Oct-2017 09:36:17.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Mac OS X
05-Oct-2017 09:36:17.609 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.12.6
05-Oct-2017 09:36:17.609 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          x86_64
05-Oct-2017 09:36:17.609 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
05-Oct-2017 09:36:17.610 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           9+181
05-Oct-2017 09:36:17.610 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
05-Oct-2017 09:36:17.610 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/Cellar/tomcat/8.5.23/libexec
05-Oct-2017 09:36:17.611 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/Cellar/tomcat/8.5.23/libexec
05-Oct-2017 09:36:17.612 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/Cellar/tomcat/8.5.23/libexec/conf/logging.properties
05-Oct-2017 09:36:17.613 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
05-Oct-2017 09:36:17.613 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
05-Oct-2017 09:36:17.614 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
05-Oct-2017 09:36:17.615 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dspring.profiles.active=local
05-Oct-2017 09:36:17.616 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Deth.config.dir=/tmp/tomcat8
05-Oct-2017 09:36:17.616 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/Cellar/tomcat/8.5.23/libexec
05-Oct-2017 09:36:17.617 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/Cellar/tomcat/8.5.23/libexec
05-Oct-2017 09:36:17.618 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/Cellar/tomcat/8.5.23/libexec/temp
05-Oct-2017 09:36:17.618 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/vobbilis/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
05-Oct-2017 09:36:17.687 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
05-Oct-2017 09:36:17.730 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
05-Oct-2017 09:36:17.734 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
05-Oct-2017 09:36:17.737 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
05-Oct-2017 09:36:17.738 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 737 ms
05-Oct-2017 09:36:17.856 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
05-Oct-2017 09:36:17.857 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.23
05-Oct-2017 09:36:17.901 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/Cellar/tomcat/8.5.23/libexec/webapps/cakeshop.war]
05-Oct-2017 09:36:17.923 WARNING [localhost-startStop-1] org.apache.catalina.startup.SetContextPropertiesRule.begin [SetContextPropertiesRule]{Context} Setting property 'antiJARLocking' to 'true' did not find a matching property.
05-Oct-2017 09:36:21.092 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
 INFO 2017-10-05 09:36:27,642 [localhost-startStop-1] (StartupInfoLogger.java:48 ) Starting WebAppInit v0.9.1 on tests-MacBook-Pro-2.local with PID 75673 (/usr/local/Cellar/tomcat/8.5.23/libexec/webapps/cakeshop/WEB-INF/classes started by vobbilis in /usr/local/Cellar/tomcat/8.5.23/libexec/bin)
 INFO 2017-10-05 09:36:27,646 [localhost-startStop-1] (SpringApplication.java:670) The following profiles are active: local
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/usr/local/Cellar/tomcat/8.5.23/libexec/webapps/cakeshop/WEB-INF/lib/spring-core-4.2.8.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
 INFO 2017-10-05 09:36:30,255 [localhost-startStop-1] (AppConfig.java:113) eth.config.dir=/private/tmp/tomcat8/local
 INFO 2017-10-05 09:36:30,258 [localhost-startStop-1] (AppConfig.java:96 ) Initializing new config from /usr/local/Cellar/tomcat/8.5.23/libexec/webapps/cakeshop/WEB-INF/classes/config/application-local.properties
 INFO 2017-10-05 09:36:30,262 [localhost-startStop-1] (AppConfig.java:144) Loading config from /private/tmp/tomcat8/local/application.properties
 WARN 2017-10-05 09:36:30,809 [localhost-startStop-1] (AbstractApplicationContext.java:546) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration$DispatcherServletConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.boot.autoconfigure.web.ServerProperties org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration$DispatcherServletConfiguration.server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties' defined in class path resource [org/springframework/boot/autoconfigure/web/ServerPropertiesAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
ERROR 2017-10-05 09:36:30,825 [localhost-startStop-1] (SpringApplication.java:827) Application startup failed
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration$DispatcherServletConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.boot.autoconfigure.web.ServerProperties org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration$DispatcherServletConfiguration.server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties' defined in class path resource [org/springframework/boot/autoconfigure/web/ServerPropertiesAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException

```
[stacktrace/logs]
```

**Comment by bmcd87** [comment]
Looks like the same issue as #61
