### ISSUE TITLE
Project status - abandoned?

### ISSUE THREAD

**Issue by drasko** [jpmorganchase/cakeshop#58]
Is this project abandoned?

**Comment by eolszewski** [comment]
Looks like it

**Comment by patrickmn** [comment]
Cakeshop has not been abandoned. There are a few blocking issues and we hope to address them soon. We warmly welcome pull requests to address existing issues and expand functionality.

**Comment by arlohosk** [comment]
Hi @patrickmn , do you happen to have an idea when those blocking issues might be fixed (e.g. 1, 3, 6 months?). Is there a major/breaking update to cakeshop coming at that point?
