### ISSUE TITLE
Invalid or Missing Value for Params when calling GET or READ on contract

### ISSUE THREAD

**Issue by deefresh** [jpmorganchase/cakeshop#60]
#### Description of problem
When I make a call to contract/get or contract/read (either through the cakeshop API dashboard or through C# code) it returns the error:  "APIException: RPC request failed: invalid or missing value for params[0]"

I suspect the issue is I am passing in the wrong "id" value for the Contract ID but I am not sure what value to send it. I am using the address value generated after a contract is deployed/registered (ex. "0xb7082611b3d4e13bccf61c4e0564f9bca146b0aa")

#### Expected behavior

Expected behavior is contract information would be returned when making call to contract/get or contract/read

#### Actual behavior

CURL generated by cakeshop api dashboard:
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"id":"0xb7082611b3d4e13bccf61c4e0564f9bca146b0aa"}' 'http://localhost:8080/cakeshop/api/contract/get'

JSON Response from cakeshop:
{
  "errors": [
    {
      "status": "500",
      "title": "Internal server error",
      "detail": "APIException: RPC request failed: invalid or missing value for params[0]"
    }
  ],
  "meta": {
    "version": "1.0",
    "cakeshop-version": "0.9.1",
    "cakeshop-build-id": "6c7a88ee8b317fe2b69c97fe1e838112cb655411",
    "cakeshop-build-date": "2017-01-03T15:42:16.969-0500"
  }
}
#### Steps to reproduce the behavior

1. Deploy a contract from the cakeshop editor or from C# code
2. Make a call to contract/get or contract/read using the address value generated from the deployed contract.
3. Cakeshop will respond with the error "APIException: RPC request failed: invalid or missing value for params[0]"

#### System information

Cakeshop 0.9.1
Build 6c7a88ee

Startup parameters: -Dgeth.node=geth

Geth Version 1.7.3-stable

Windows 10 / i7

Windows Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by deefresh** [comment]
For what it's worth, I get the same error/behavior on Cakeshop 0.10.0

**Comment by bmcd87** [comment]
Way late on this, but yes it should be the Contract Address, not the transaction ID. And the key that the api/contract/get is expecting is "address" not "id"
