### ISSUE TITLE
cakeshop docker don't start while it works on other

### ISSUE THREAD

**Issue by Archie1978** [jpmorganchase/cakeshop#66]
Can not start the cakeshop docker ( the last version and 0.9.0 ) because the wallets do not unlocked. 

"docker run -p 8080:8080 -v "$PWD/data":/opt/cakeshop/data     -e JAVA_OPTS="-Dspring.profiles.active=local"     jpmc/cakeshop"

I tried to delete wallet that were not unlocked but apparently it is still the last wallets that does not unlocked.
I do not understand why image docker does not work on this computer (ubuntu 16.04.03) only.

I0424 17:05:25.214766 core/blockchain.go:221] Fast block: #0 [d93b8da4…] TD=1024
I0424 17:05:25.215946 p2p/server.go:342] Starting Server
I0424 17:05:25.216223 p2p/server.go:610] Listening on [::]:30303
I0424 17:05:25.216243 eth/backend.go:473] Automatic pregeneration of ethash DAG ON (ethash dir: /opt/cakeshop/.ethash)
I0424 17:05:25.216960 eth/backend.go:480] checking DAG (ethash dir: /opt/cakeshop/.ethash)
I0424 17:05:25.220464 node/node.go:411] HTTP endpoint opened: http://127.0.0.1:8102
 INFO 2018-04-24 17:05:25,417 [main] (GethHttpServiceImpl.java:535) Geth RPC endpoint is up
 INFO 2018-04-24 17:05:25,564 [main] (GethHttpServiceImpl.java:496) Waiting up to 6000ms for 3 accounts to unlock
I0424 17:05:27.771006 cmd/geth/accountcmd.go:200] Unlocked account 2e219248f44546d966808cdd20cb6c36df6efa82
I0424 17:05:30.297468 cmd/geth/accountcmd.go:200] Unlocked account cd5b17da5ad176905c12fc85ce43ec287ab55363
ERROR 2018-04-24 17:05:31,564 [main] (GethHttpServiceImpl.java:568) Wallet did not unlock in a timely manner (2 of 3 accounts unlocked)
ERROR 2018-04-24 17:05:31,577 [main] (GethHttpServiceImpl.java:568) Ethereum failed to start
org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@435d8d56: startup date [Tue Apr 24 17:05:05 UTC 2018]; root of context hierarchy

One idea ?

**Comment by fixanoid** [comment]
Hi, looks like the wallet didn't get unlocked in timeout time. Please play around with application.properties file and `geth.unlock.timeout=10000` and try again.
