### ISSUE TITLE
Is there a way to Turn Mining On/Off?

### ISSUE THREAD

**Issue by deefresh** [jpmorganchase/cakeshop#75]
Is there any way to make a call to a cakeshop api to turn the geth miner on and off?

It looks like Cakeshop itself has some code to do it when you are on the Sandbox page and hit the play/pause button. Code appears to be this:

Map<String, Object> res = geth.executeGethCall("miner_stop", new Object[]{});

Is there any place Cakeshop exposes that? Or do I need to make an RPC call to geth from my own application to turn it off?

**Comment by fixanoid** [comment]
Hi @deefresh there is, and its wrapped as part of the NodeController update method as described here:
https://github.com/jpmorganchase/cakeshop/blob/master/cakeshop-api/src/main/java/com/jpmorgan/cakeshop/controller/NodeController.java#L96

You need to change the value of commitingTransactions to true or false.
