### ISSUE TITLE
Cakeshop not compatible with RAFT Consensus, Getting the following error "Failed to connect to RPC,  invalid argument 1: json: cannot unmarshal hex string without 0x prefix into Go value of type hexutil.Bytes"

### ISSUE THREAD

**Issue by Ajaysethi136** [jpmorganchase/cakeshop#76]
I'm trying to integrate Cakeshop with the Quorum node(Using Raft Consensus), but it is taking Voting Parameters which is part of old Quorum Chain(Voting Consensus Model), it is no longer in use now but the cakeshop repo is not updated since then.

I'm running 4 nodes in different different VM's.

 Getting the following error "Failed to connect to RPC,  invalid argument 1: json: cannot unmarshal hex string without 0x prefix into Go value of type hexutil.Bytes"

Is it compatible with IBFT?

Can anyone please help.

Regards,
Ajay

**Comment by fixanoid** [comment]
@Ajaysethi136 current release of cakeshop only supports Quorum v1, so no Raft or IBFT yet. Theres been some work done in the pull. Check it out? https://github.com/jpmorganchase/cakeshop/pull/72

**Comment by Ajaysethi136** [comment]
@fixanoid  Do you have any suggestion whether we should integrate our Quorum Nodes using RAFT with cakeshop or not if somehow we make it work with RAFT bby making few changes in Cakeshop code??

**Comment by Ajaysethi136** [comment]
@fixanoid do I need to incorporate all the changes committed by @yourcodesucks in the current version of cakeshop? or Is it already incorporated into the current version 0.10 of cakeshop, if yes, but i'm facing error while integrating the current version of cakeshop "Failed to connect to RPC, invalid argument 1: json: cannot unmarshal hex string without 0x prefix into Go value of type hexutil.Bytes".

Kindly suggest.

**Comment by fixanoid** [comment]
Hi, you either use yourcodesucks fork or quorum-ui branch. Master is too
old at the moment.

**Comment by Aghorb** [comment]
@Ajaysethi136 have you solve the problem? I'm facing the same prob and I would like to know what happened with you.
I'm working on ubuntu 16.04
cakeshop 0.10.0
quorum 7nodes example
