### ISSUE TITLE
No Manifest attribute found while building the cakeshop war file.

### ISSUE THREAD

**Issue by Ajaysethi136** [jpmorganchase/cakeshop#77]
I've made some changes in cakeshop code, post which I'm generating a war file with the modified code, 

I'm facing the following error "No Manifest attribute found".

I'm not aware of the main class in cakeshop code.

Regards,
Ajay

**Comment by fixanoid** [comment]
@Ajaysethi136 where is this error being generated? Cakeshop is several projects in one, so not all of them have a main, but cakeshop-api is the Spring Boot app that does have one, see: https://github.com/jpmorganchase/cakeshop/blob/master/cakeshop-api/src/main/java/com/jpmorgan/cakeshop/config/SpringBootApplication.java
