### ISSUE TITLE
Gradle/Maven Build to Include Spring LDAP

### ISSUE THREAD

**Issue by nathanawmk** [jpmorganchase/cakeshop#83]
#### Description of problem
Include Spring LDAP integration and using Gradle/Maven Build. Is there some way to include this and rebuild it?

#### Expected behavior
Include Spring LDAP integration and using Gradle/Maven Build?
https://docs.spring.io/spring-ldap/docs/current/reference/

#### Actual behavior

(paste logs at end)

#### System information

Cakeshop version or commit hash: [version]

Cakeshop runtime configuration: [stand alone or attach mode]

Geth/Quorum version testing against: [run `geth version` or copy from Node Info in UI]

Cakeshop OS & Version: Windows/Linux/OSX

Browser OS & Version: Windows/Linux/OSX MSIE/Chrome/Firefox/Safari

#### Backtrace/logs

Copy all relevant log output. Use [Gist](https://gist.github.com/) for longer logs.

```
[stacktrace/logs]
```

**Comment by bmcd87** [comment]
This is related to #86
