### ISSUE TITLE
SQL error in terminal window. See gist

### ISSUE THREAD

**Issue by rfikki** [jpmorganchase/cakeshop#9]
#### Description of problem
SQL error in terminal window.

#### Actual behavior
https://gist.github.com/rfikki/9c1e53c0f21568f13f9aba64203b27f4
(paste logs at end)

#### Steps to reproduce the behavior
Not sure what caused it

#### System information
Win 10 64Bit
Cakeshop version or commit hash: [version]
0.90
Geth/Quorum version testing against: [run `geth version` or copy from Node Info in UI]

Cakeshop OS & Version: Windows/Linux/OSX

Browser OS & Version: Windows/Linux/OSX MSIE/Chrome/Firefox/Safari
Chrome latest
#### Backtrace/logs

Copy all relevant log output. Use [Gist](https://gist.github.com/) for longer logs.
https://gist.github.com/rfikki/9c1e53c0f21568f13f9aba64203b27f4
```
[stacktrace/logs]
```

**Comment by chetan** [comment]
I think this may just be due to the local db getting out of whack from previous tries to run it. Can you delete the folder at `data/local/db` and try starting Cakeshop again? It should resynchronize the database automatically on startup.

**Comment by rfikki** [comment]
I will delete the db shortly and report back. I ran cakeshop against the public ropsten testnet on Windows 10 overnight, with relatively few errors. It is looking great.

**Comment by rfikki** [comment]
So, I renamed the db directory to something else, closed and restarted Cakeshop. A new db directory was created, received repeated multiple errors in the terminal. shut down Cakeshop, went back and changed the db directory back to my old one and it runs fine so except for this SQL error in the terminal: 
https://gist.github.com/rfikki/6207e9f7a550f1e189bfd87c3b9c1bd1

**Comment by rfikki** [comment]
Seems to be running great now. Thanks for the assistance!
https://gist.github.com/rfikki/4e37069e96d661a4d4552e0e1a50e59f
