### ISSUE TITLE
java -jar -Dgeth.node=geth cakeshop.war

### ISSUE THREAD

**Issue by xblox** [jpmorganchase/cakeshop#91]
Hi,

I run java -jar -Dgeth.node=geth cakeshop.war and mined more than 10k blocks and it's still running(windows).
How many blocks do I have to mine in total or it will stop automatically?

Thanks!  

[DEBUG] 2019-04-10 21:00:40.884 [StreamLogAdapter] geth - I0410 20:55:48.767122 miner/worker.go:443] ­ƒö¿ ­ƒöù  Mined 5 blocks back: block #10901
[DEBUG] 2019-04-10 21:00:40.885 [StreamLogAdapter] geth - I0410 20:56:39.860833 miner/worker.go:347] ­ƒö¿  Mined block (#10907 / 0ba2eea4). Wait 5 blocks for confirmation
[DEBUG] 2019-04-10 21:00:40.885 [StreamLogAdapter] geth - I0410 20:56:39.862833 miner/worker.go:548] commit new work on block 10908 with 0 txs & 0 uncles. Took 1.9994ms
[DEBUG] 2019-04-10 21:00:40.886 [StreamLogAdapter] geth - I0410 20:56:39.862833 miner/worker.go:443] ­ƒö¿ ­ƒöù  Mined 5 blocks back: block #10902
[DEBUG] 2019-04-10 21:00:40.888 [StreamLogAdapter] geth - I0410 20:57:11.286732 miner/worker.go:347] ­ƒö¿  Mined block (#10908 / 928a7aa2). Wait 5 blocks for confirmation
[DEBUG] 2019-04-10 21:00:40.900 [StreamLogAdapter] geth - I0410 20:57:11.287732 miner/worker.go:548] commit new work on block 10909 with 0 txs & 0 uncles. Took 999.9┬Ás
[DEBUG] 2019-04-10 21:00:40.900 [StreamLogAdapter] geth - I0410 20:57:11.287732 miner/worker.go:443] ­ƒö¿ ­ƒöù  Mined 5 blocks back: block #10903
[DEBUG] 2019-04-10 21:00:40.901 [StreamLogAdapter] geth - I0410 20:58:25.213587 miner/worker.go:347] ­ƒö¿  Mined block (#10909 / 830df444). Wait 5 blocks for confirmation
[DEBUG] 2019-04-10 21:00:40.902 [StreamLogAdapter] geth - I0410 20:58:25.214586 miner/worker.go:548] commit new work on block 10910 with 0 txs & 0 uncles. Took 999.6┬Ás
[DEBUG] 2019-04-10 21:00:40.903 [StreamLogAdapter] geth - I0410 20:58:25.215585 miner/worker.go:443] ­ƒö¿ ­ƒöù  Mined 5 blocks back: block #10904
[DEBUG] 2019-04-10 21:00:40.904 [StreamLogAdapter] geth - I0410 20:58:27.956471 miner/worker.go:347] ­ƒö¿  Mined block (#10910 / efe60275). Wait 5 blocks for confirmation
[DEBUG] 2019-04-10 21:00:40.904 [StreamLogAdapter] geth - I0410 20:58:27.957470 miner/worker.go:548] commit new work on block 10911 with 0 txs & 0 uncles. Took 999┬Ás
[DEBUG] 2019-04-10 21:00:40.905 [StreamLogAdapter] geth - I0410 20:58:27.957470 miner/worker.go:443] ­ƒö¿ ­ƒöù  Mined 5 blocks back: block #10905
[DEBUG] 2019-04-10 21:00:40.906 [StreamLogAdapter] geth - I0410 20:58:39.131663 miner/worker.go:347] ­ƒö¿  Mined block (#10911 / 8f569c61). Wait 5 blocks for confirmation
[DEBUG] 2019-04-10 21:00:40.906 [StreamLogAdapter] geth - I0410 20:58:39.133662 miner/worker.go:548] commit new work on block 10912 with 0 txs & 0 uncles. Took 1.9986ms
[DEBUG] 2019-04-10 21:00:40.907 [StreamLogAdapter] geth - I0410 21:00:40.874086 miner/worker.go:443] ­ƒö¿ ­ƒöù  Mined 5 blocks back: block #10906

**Comment by bmcd87** [comment]
Right now we’re focused on making cakeshop work with Quorum. We haven’t fully tried connecting to the Ethereum mainnet like that, as it will take a very long time to sync up all the blocks.

More info here: https://github.com/ethereumbook/ethereumbook/blob/develop/03clients.asciidoc#the-first-synchronization-of-ethereum-based-blockchains
