### ISSUE TITLE
contract compiled error: Expected identifier, got 'LParen'  constructor(string ric_name, string fid_name1, string fid_name2) public {

### ISSUE THREAD

**Issue by maxzq** [jpmorganchase/cakeshop#98]
#### Description of problem
cakeshop sandbox compiler output error above while it is work for my ethereum and remix and truffle. 
not quit sure what is difference between cakeshop and standary remix/truffle, looks like it is solc version but i am not 100% sure. 
#### Expected behavior
contract should be complied without error
#### Actual behavior
:44:16: Error: Expected identifier, got 'LParen'
    constructor(string ric_name, string fid_name1, string fid_name2) public {

#### System information

Cakeshop version or commit hash: [cakeshop version: Cakeshop 0.9.1 Build 6c7a88ee]

Cakeshop runtime configuration: [ attach mode]

Geth/Quorum version testing against: [Geth/v1.8.18-stable-8f19fb1e(quorum-v2.2.3)/linux-amd64/go1.10.4]

Cakeshop OS & Version:  linux-amd64

Browser OS & Version: Window/Chrome
#### Backtrace/logs

Copy all relevant log output. Use [Gist](https://gist.github.com/) for longer logs.

```
[stacktrace/logs]
```

**Comment by bmcd87** [comment]
Please try the latest version of cakeshop (0.11.0) from the releases page. It uses solc 0.5.x
