### ISSUE TITLE
what is contract registry address? 

### ISSUE THREAD

**Issue by maxzq** [jpmorganchase/cakeshop#99]
#### Description of problem
run cakeshop in attach way follow attch section instruction  from below address https://github.com/jpmorganchase/cakeshop/wiki/Getting-Started

, it always failed with below error then failed  

 INFO 2019-05-10 10:09:47,380 [main] (BlockchainInitializerTask.java:120) Contract registry address not found
 INFO 2019-05-10 10:09:47,381 [main] (BlockchainInitializerTask.java:149) ContractRegistry not found on chain
 INFO 2019-05-10 10:09:47,384 [main] (BlockchainInitializerTask.java:154) Deploying ContractRegistry to chain

ERROR 2019-05-10 10:09:50,507 [main] (ContractServiceImpl.java:120) REASON FOR CONTRATC FAILURE Unexpected end-of-input: was expecting closing quote for a string value
#### Actual behavior

(paste logs at end)

#### System information

Cakeshop version or commit hash: [Cakeshop 0.9.1Build 6c7a88ee]

Cakeshop runtime configuration: [attach mode]

Geth/Quorum version testing against: [Geth/v1.8.18-stable-8f19fb1e(quorum-v2.2.3)]

Cakeshop OS & Version: linux-amd64/ 

Browser OS & Version: Windows/Chrome

#### Backtrace/logs

Copy all relevant log output. Use [Gist](https://gist.github.com/) for longer logs.

```
[stacktrace/logs]
```

**Comment by bmcd87** [comment]
The contract registry is a special smart contract that keeps track of the addresses, abi, and solidity code of contracts deployed through cakeshop's sandbox. It no longer deploys on its own, instead you deploy it from the Contract tab once you attach to a node. Please try the newest version of cakeshop from the releases page.
